# Generated by Django 5.1.6 on 2025-02-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='refills_allowed',
            field=models.IntegerField(default=0),
        ),
    ]
