# Generated by Django 5.1.6 on 2025-02-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_prescription_refills_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
